default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: story_journal_server_dev
  username: storyjournaladmin
  password: storyjournal2019

test:
  <<: *default
  database: story_journal_server_test
  username: storyjournaladmin
  password: storyjournal2019
